<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.01" os="Windows 7" host="HW1419"><DocLocation><![CDATA[C:\IFSAutomation\Finance\Drivers\SuiteDriver]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[SuiteDriver]]></DName>
<Res><![CDATA[Res457]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Step rID="T3">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Wrong number of arguments or invalid property assignment: 'SelectCheckBox'<BR>Function file: C:\IFSAutomation\Finance\Libraries\GeneralLibraries\RegisteredFunctions.vbs<BR>Line (1815): &quot;SelectCheckBox&quot;.]]></Details>
<Time><![CDATA[18-11-2016 - 19:13:23]]></Time>
<TimeTick>1479476603</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="6" status="Failed" Source="C:\IFSAutomation\Finance\Libraries\GeneralLibraries\RegisteredFunctions.vbs" SourceLine="1814" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[18-11-2016 - 19:14:17]]></Time>
<TimeTick>1479476657</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "iexplore.exe",3]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "iexplore.exe",3]]></Details>
<Time><![CDATA[18-11-2016 - 19:14:17]]></Time>
<TimeTick>1479476657</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" >
<Disp><![CDATA[Run "iexplore.exe",3]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj ><![CDATA[LoginToSecurityWindow]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[18-11-2016 - 19:14:27]]></Time>
<TimeTick>1479476667</TimeTick>
<NodeArgs eType="User" icon="6" nRep="12" status="Passed" >
<Disp><![CDATA[LoginToSecurityWindow]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:27]]></Time>
<TimeTick>1479476727</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Windows Security]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:27]]></Time>
<TimeTick>1479476727</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[txt_UserName.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:27]]></Time>
<TimeTick>1479476727</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="15" >
<Disp><![CDATA[txt_UserName.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[txt_UserName.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["Gallop@IFSAutomation.com"]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:27]]></Time>
<TimeTick>1479476727</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="17" >
<Disp><![CDATA[txt_UserName.SetText]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="14" >
<Disp><![CDATA[Windows Security]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="13" >
<Disp><![CDATA[Browser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj ><![CDATA[LoginToSecurityWindow]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:27]]></Time>
<TimeTick>1479476727</TimeTick>
<NodeArgs eType="User" icon="6" nRep="18" status="Passed" >
<Disp><![CDATA[LoginToSecurityWindow]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:27]]></Time>
<TimeTick>1479476727</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Windows Security]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:27]]></Time>
<TimeTick>1479476727</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[txt_PassWord.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:27]]></Time>
<TimeTick>1479476727</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="21" >
<Disp><![CDATA[txt_PassWord.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[txt_PassWord.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["Password2016!"]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:27]]></Time>
<TimeTick>1479476727</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="23" >
<Disp><![CDATA[txt_PassWord.SetText]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="20" >
<Disp><![CDATA[Windows Security]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="19" >
<Disp><![CDATA[Browser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj ><![CDATA[LoginToSecurityWindow]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:27]]></Time>
<TimeTick>1479476727</TimeTick>
<NodeArgs eType="User" icon="6" nRep="24" status="Passed" >
<Disp><![CDATA[LoginToSecurityWindow]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:27]]></Time>
<TimeTick>1479476727</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Windows Security]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:27]]></Time>
<TimeTick>1479476727</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[btn_OK.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:27]]></Time>
<TimeTick>1479476727</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="27" >
<Disp><![CDATA[btn_OK.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[btn_OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:27]]></Time>
<TimeTick>1479476727</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="29" >
<Disp><![CDATA[btn_OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="26" >
<Disp><![CDATA[Windows Security]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="25" >
<Disp><![CDATA[Browser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj ><![CDATA[LoginToSecurityWindow]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:27]]></Time>
<TimeTick>1479476727</TimeTick>
<NodeArgs eType="User" icon="6" nRep="30" status="Passed" >
<Disp><![CDATA[LoginToSecurityWindow]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:36]]></Time>
<TimeTick>1479476736</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:36]]></Time>
<TimeTick>1479476736</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[btn_Login.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:36]]></Time>
<TimeTick>1479476736</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="34" >
<Disp><![CDATA[btn_Login.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="33" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="32" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj ><![CDATA[LoginToFinance]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:39]]></Time>
<TimeTick>1479476739</TimeTick>
<NodeArgs eType="User" icon="6" nRep="35" status="Passed" >
<Disp><![CDATA[LoginToFinance]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:39]]></Time>
<TimeTick>1479476739</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:39]]></Time>
<TimeTick>1479476739</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[txt_UserName.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:39]]></Time>
<TimeTick>1479476739</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="39" >
<Disp><![CDATA[txt_UserName.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[txt_UserName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["cj"]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:39]]></Time>
<TimeTick>1479476739</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="41" >
<Disp><![CDATA[txt_UserName.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="38" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="37" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj ><![CDATA[LoginToFinance]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:39]]></Time>
<TimeTick>1479476739</TimeTick>
<NodeArgs eType="User" icon="6" nRep="42" status="Passed" >
<Disp><![CDATA[LoginToFinance]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:39]]></Time>
<TimeTick>1479476739</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:39]]></Time>
<TimeTick>1479476739</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[txt_Password.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:39]]></Time>
<TimeTick>1479476739</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="46" >
<Disp><![CDATA[txt_Password.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[txt_Password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["password"]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:39]]></Time>
<TimeTick>1479476739</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="48" >
<Disp><![CDATA[txt_Password.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="45" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="44" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj ><![CDATA[LoginToFinance]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:39]]></Time>
<TimeTick>1479476739</TimeTick>
<NodeArgs eType="User" icon="6" nRep="49" status="Passed" >
<Disp><![CDATA[LoginToFinance]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:39]]></Time>
<TimeTick>1479476739</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:39]]></Time>
<TimeTick>1479476739</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[btn_Login.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:39]]></Time>
<TimeTick>1479476739</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="53" >
<Disp><![CDATA[btn_Login.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[btn_Login.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:39]]></Time>
<TimeTick>1479476739</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="55" >
<Disp><![CDATA[btn_Login.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="52" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="51" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj ><![CDATA[LoginToFinance]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:39]]></Time>
<TimeTick>1479476739</TimeTick>
<NodeArgs eType="User" icon="6" nRep="56" status="Passed" >
<Disp><![CDATA[LoginToFinance]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:45]]></Time>
<TimeTick>1479476745</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Work Queue]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:45]]></Time>
<TimeTick>1479476745</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[lnk_Certificates.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:45]]></Time>
<TimeTick>1479476745</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="60" >
<Disp><![CDATA[lnk_Certificates.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="59" >
<Disp><![CDATA[Work Queue]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="58" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj ><![CDATA[LoginToFinance]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:45]]></Time>
<TimeTick>1479476745</TimeTick>
<NodeArgs eType="User" icon="6" nRep="61" status="Passed" >
<Disp><![CDATA[LoginToFinance]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:45]]></Time>
<TimeTick>1479476745</TimeTick>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Work Queue]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:45]]></Time>
<TimeTick>1479476745</TimeTick>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[lnk_Certificates.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:45]]></Time>
<TimeTick>1479476745</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="65" >
<Disp><![CDATA[lnk_Certificates.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="64" >
<Disp><![CDATA[Work Queue]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="63" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj ><![CDATA[LoginToFinance]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:45]]></Time>
<TimeTick>1479476745</TimeTick>
<NodeArgs eType="User" icon="6" nRep="66" status="Passed" >
<Disp><![CDATA[LoginToFinance]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:49]]></Time>
<TimeTick>1479476749</TimeTick>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Work Queue]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:49]]></Time>
<TimeTick>1479476749</TimeTick>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[lnk_Certificates.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:49]]></Time>
<TimeTick>1479476749</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="70" >
<Disp><![CDATA[lnk_Certificates.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[lnk_Certificates.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:49]]></Time>
<TimeTick>1479476749</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="72" >
<Disp><![CDATA[lnk_Certificates.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="69" >
<Disp><![CDATA[Work Queue]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="68" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj ><![CDATA[NavigateToEntryRequestDetails]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:49]]></Time>
<TimeTick>1479476749</TimeTick>
<NodeArgs eType="User" icon="6" nRep="73" status="Passed" >
<Disp><![CDATA[NavigateToEntryRequestDetails]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:49]]></Time>
<TimeTick>1479476749</TimeTick>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Work Queue]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:49]]></Time>
<TimeTick>1479476749</TimeTick>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[lnk_CreateRequest.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:49]]></Time>
<TimeTick>1479476749</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="77" >
<Disp><![CDATA[lnk_CreateRequest.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[lnk_CreateRequest.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:49]]></Time>
<TimeTick>1479476749</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="79" >
<Disp><![CDATA[lnk_CreateRequest.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="76" >
<Disp><![CDATA[Work Queue]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="75" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj ><![CDATA[NavigateToEntryRequestDetails]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:49]]></Time>
<TimeTick>1479476749</TimeTick>
<NodeArgs eType="User" icon="6" nRep="80" status="Passed" >
<Disp><![CDATA[NavigateToEntryRequestDetails]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:54]]></Time>
<TimeTick>1479476754</TimeTick>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[EntrerRequestDetails]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:54]]></Time>
<TimeTick>1479476754</TimeTick>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[btn_SelectClient.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:54]]></Time>
<TimeTick>1479476754</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="84" >
<Disp><![CDATA[btn_SelectClient.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="83" >
<Disp><![CDATA[EntrerRequestDetails]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="82" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj ><![CDATA[NavigateToEntryRequestDetails]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[18-11-2016 - 19:15:57]]></Time>
<TimeTick>1479476757</TimeTick>
<NodeArgs eType="User" icon="6" nRep="85" status="Passed" >
<Disp><![CDATA[NavigateToEntryRequestDetails]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[18-11-2016 - 19:16:03]]></Time>
<TimeTick>1479476763</TimeTick>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[EntrerRequestDetails]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[18-11-2016 - 19:16:03]]></Time>
<TimeTick>1479476763</TimeTick>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[btn_SelectClient.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[18-11-2016 - 19:16:03]]></Time>
<TimeTick>1479476763</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="89" >
<Disp><![CDATA[btn_SelectClient.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="88" >
<Disp><![CDATA[EntrerRequestDetails]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="87" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj ><![CDATA[NavigateToEntryRequestDetails]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[18-11-2016 - 19:16:03]]></Time>
<TimeTick>1479476763</TimeTick>
<NodeArgs eType="User" icon="6" nRep="90" status="Passed" >
<Disp><![CDATA[NavigateToEntryRequestDetails]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[18-11-2016 - 19:16:03]]></Time>
<TimeTick>1479476763</TimeTick>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[EntrerRequestDetails]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[18-11-2016 - 19:16:03]]></Time>
<TimeTick>1479476763</TimeTick>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[btn_SelectClient.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[18-11-2016 - 19:16:03]]></Time>
<TimeTick>1479476763</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="94" >
<Disp><![CDATA[btn_SelectClient.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[btn_SelectClient.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[18-11-2016 - 19:16:03]]></Time>
<TimeTick>1479476763</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="96" >
<Disp><![CDATA[btn_SelectClient.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="93" >
<Disp><![CDATA[EntrerRequestDetails]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="92" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj ><![CDATA[NavigateToEntryRequestDetails]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[18-11-2016 - 19:16:03]]></Time>
<TimeTick>1479476763</TimeTick>
<NodeArgs eType="User" icon="6" nRep="97" status="Passed" >
<Disp><![CDATA[NavigateToEntryRequestDetails]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[18-11-2016 - 19:16:11]]></Time>
<TimeTick>1479476771</TimeTick>
<Step rID="T74">
<Obj plainTxt="False" ><![CDATA[Client Search]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[18-11-2016 - 19:16:11]]></Time>
<TimeTick>1479476771</TimeTick>
<Step rID="T75">
<Obj plainTxt="False" ><![CDATA[btn_Search.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[18-11-2016 - 19:16:11]]></Time>
<TimeTick>1479476771</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="101" >
<Disp><![CDATA[btn_Search.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="100" >
<Disp><![CDATA[Client Search]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="99" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T76">
<Obj ><![CDATA[EnterClientName]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[18-11-2016 - 19:16:11]]></Time>
<TimeTick>1479476771</TimeTick>
<NodeArgs eType="User" icon="6" nRep="102" status="Passed" >
<Disp><![CDATA[EnterClientName]]></Disp>
</NodeArgs>
</Step>
<Step rID="T77">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[18-11-2016 - 19:16:11]]></Time>
<TimeTick>1479476771</TimeTick>
<Step rID="T78">
<Obj plainTxt="False" ><![CDATA[Client Search]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[18-11-2016 - 19:16:11]]></Time>
<TimeTick>1479476771</TimeTick>
<Step rID="T79">
<Obj plainTxt="False" ><![CDATA[lbl_ClientSearchCriteria.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[18-11-2016 - 19:16:11]]></Time>
<TimeTick>1479476771</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="106" >
<Disp><![CDATA[lbl_ClientSearchCriteria.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="105" >
<Disp><![CDATA[Client Search]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="104" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T80">
<Obj ><![CDATA[EnterClientName]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[18-11-2016 - 19:16:11]]></Time>
<TimeTick>1479476771</TimeTick>
<NodeArgs eType="User" icon="6" nRep="107" status="Passed" >
<Disp><![CDATA[EnterClientName]]></Disp>
</NodeArgs>
</Step>
<Step rID="T81">