<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.01" os="Windows 7" host="HW1419"><DocLocation><![CDATA[C:\IFSAutomation\Trunk_IFS_QuestionTypes\Drivers\SuiteDriver]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[SuiteDriver]]></DName>
<Res><![CDATA[Res388]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Provider cannot be found. It may not be properly installed.<BR>Function file: C:\IFSAutomation\Trunk_IFS_QuestionTypes\Libraries\GeneralLibraries\Utilities.vbs<BR>Line (45): &quot;		objExcel.Open &quot;Provider=Microsoft.ACE.OLEDB.12.0;;Extended Properties=Excel 12.0;Data Source=&quot;&amp;file&amp;&quot;;&quot;&quot;.]]></Details>
<Time><![CDATA[21-06-2016 - 15:44:10]]></Time>
<TimeTick>1466504050</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="7" status="Failed" Source="C:\IFSAutomation\Trunk_IFS_QuestionTypes\Libraries\GeneralLibraries\Utilities.vbs" SourceLine="44" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The connection cannot be used to perform this operation. It is either closed or invalid in this context.<BR>Function file: C:\IFSAutomation\Trunk_IFS_QuestionTypes\Libraries\GeneralLibraries\Utilities.vbs<BR>Line (46): &quot;		objRS.Open &quot;Select * from [&quot;&amp;sheet&amp;&quot;$] where TestcaseId='&quot;&amp;id&amp;&quot;' And Execute = 'Y'&quot;, objExcel, adOpenStatic&quot;.]]></Details>
<Time><![CDATA[21-06-2016 - 15:44:10]]></Time>
<TimeTick>1466504050</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="8" status="Failed" Source="C:\IFSAutomation\Trunk_IFS_QuestionTypes\Libraries\GeneralLibraries\Utilities.vbs" SourceLine="45" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Item cannot be found in the collection corresponding to the requested name or ordinal.<BR>Function file: C:\IFSAutomation\Trunk_IFS_QuestionTypes\Libraries\GeneralLibraries\Utilities.vbs<BR>Line (52): &quot;			columnHeader = objRS.Fields(i).Name&quot;.]]></Details>
<Time><![CDATA[21-06-2016 - 15:44:10]]></Time>
<TimeTick>1466504050</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="9" status="Failed" Source="C:\IFSAutomation\Trunk_IFS_QuestionTypes\Libraries\GeneralLibraries\Utilities.vbs" SourceLine="51" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Operation is not allowed when the object is closed.<BR>Function file: C:\IFSAutomation\Trunk_IFS_QuestionTypes\Libraries\GeneralLibraries\Utilities.vbs<BR>Line (54): &quot;				If objRS.RecordCount = 0 Then&quot;.]]></Details>
<Time><![CDATA[21-06-2016 - 15:44:10]]></Time>
<TimeTick>1466504050</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="10" status="Failed" Source="C:\IFSAutomation\Trunk_IFS_QuestionTypes\Libraries\GeneralLibraries\Utilities.vbs" SourceLine="53" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Wrong number of arguments or invalid property assignment: 'rptReportLog'<BR>Function file: C:\IFSAutomation\Trunk_IFS_QuestionTypes\Libraries\GeneralLibraries\Utilities.vbs<BR>Line (55): &quot;					rptReportLog &quot;Records not found&quot;, &quot;Execute status should be 'Y'&quot;, &quot;Execute status is 'N'&quot;, &quot;FAIL&quot;&quot;.]]></Details>
<Time><![CDATA[21-06-2016 - 15:44:10]]></Time>
<TimeTick>1466504050</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="11" status="Failed" Source="C:\IFSAutomation\Trunk_IFS_QuestionTypes\Libraries\GeneralLibraries\Utilities.vbs" SourceLine="54" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj ><![CDATA[Read the test data from C:\IFSAutomation\Trunk_IFS_QuestionTypes\Test Data\Strings.xls File ]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[21-06-2016 - 15:44:11]]></Time>
<TimeTick>1466504051</TimeTick>
<NodeArgs eType="User" icon="5" nRep="12" status="Failed" >
<Disp><![CDATA[Read the test data from C:\IFSAutomation\Trunk_IFS_QuestionTypes\Test Data\Strings.xls File ]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Provider cannot be found. It may not be properly installed.<BR>Function file: C:\IFSAutomation\Trunk_IFS_QuestionTypes\Libraries\GeneralLibraries\Utilities.vbs<BR>Line (45): &quot;		objExcel.Open &quot;Provider=Microsoft.ACE.OLEDB.12.0;;Extended Properties=Excel 12.0;Data Source=&quot;&amp;file&amp;&quot;;&quot;&quot;.]]></Details>
<Time><![CDATA[21-06-2016 - 15:45:49]]></Time>
<TimeTick>1466504149</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="13" status="Failed" Source="C:\IFSAutomation\Trunk_IFS_QuestionTypes\Libraries\GeneralLibraries\Utilities.vbs" SourceLine="44" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The connection cannot be used to perform this operation. It is either closed or invalid in this context.<BR>Function file: C:\IFSAutomation\Trunk_IFS_QuestionTypes\Libraries\GeneralLibraries\Utilities.vbs<BR>Line (46): &quot;		objRS.Open &quot;Select * from [&quot;&amp;sheet&amp;&quot;$] where TestcaseId='&quot;&amp;id&amp;&quot;' And Execute = 'Y'&quot;, objExcel, adOpenStatic&quot;.]]></Details>
<Time><![CDATA[21-06-2016 - 15:45:49]]></Time>
<TimeTick>1466504149</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="14" status="Failed" Source="C:\IFSAutomation\Trunk_IFS_QuestionTypes\Libraries\GeneralLibraries\Utilities.vbs" SourceLine="45" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Item cannot be found in the collection corresponding to the requested name or ordinal.<BR>Function file: C:\IFSAutomation\Trunk_IFS_QuestionTypes\Libraries\GeneralLibraries\Utilities.vbs<BR>Line (52): &quot;			columnHeader = objRS.Fields(i).Name&quot;.]]></Details>
<Time><![CDATA[21-06-2016 - 15:45:49]]></Time>
<TimeTick>1466504149</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="15" status="Failed" Source="C:\IFSAutomation\Trunk_IFS_QuestionTypes\Libraries\GeneralLibraries\Utilities.vbs" SourceLine="51" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Operation is not allowed when the object is closed.<BR>Function file: C:\IFSAutomation\Trunk_IFS_QuestionTypes\Libraries\GeneralLibraries\Utilities.vbs<BR>Line (54): &quot;				If objRS.RecordCount = 0 Then&quot;.]]></Details>
<Time><![CDATA[21-06-2016 - 15:45:49]]></Time>
<TimeTick>1466504149</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="16" status="Failed" Source="C:\IFSAutomation\Trunk_IFS_QuestionTypes\Libraries\GeneralLibraries\Utilities.vbs" SourceLine="53" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Wrong number of arguments or invalid property assignment: 'rptReportLog'<BR>Function file: C:\IFSAutomation\Trunk_IFS_QuestionTypes\Libraries\GeneralLibraries\Utilities.vbs<BR>Line (55): &quot;					rptReportLog &quot;Records not found&quot;, &quot;Execute status should be 'Y'&quot;, &quot;Execute status is 'N'&quot;, &quot;FAIL&quot;&quot;.]]></Details>
<Time><![CDATA[21-06-2016 - 15:45:49]]></Time>
<TimeTick>1466504149</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="17" status="Failed" Source="C:\IFSAutomation\Trunk_IFS_QuestionTypes\Libraries\GeneralLibraries\Utilities.vbs" SourceLine="54" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj ><![CDATA[Read the test data from C:\IFSAutomation\Trunk_IFS_QuestionTypes\Test Data\RepeatingModTable.xls File ]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[21-06-2016 - 15:45:49]]></Time>
<TimeTick>1466504149</TimeTick>
<NodeArgs eType="User" icon="5" nRep="18" status="Failed" >
<Disp><![CDATA[Read the test data from C:\IFSAutomation\Trunk_IFS_QuestionTypes\Test Data\RepeatingModTable.xls File ]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'XLTDWB'<BR>Line (134): &quot;XLTDWB.Close&quot;. ]]></Details>
<Time><![CDATA[21-06-2016 - 15:46:19]]></Time>
<TimeTick>1466504179</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="19" status="Failed" Source="Action1" SourceLine="133" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'Wscript'<BR>Function file: C:\IFSAutomation\Trunk_IFS_QuestionTypes\Libraries\GeneralLibraries\CommonLibrary.vbs<BR>Line (657): &quot;	Set objNetwork = Wscript.CreateObject(&quot;Wscript.Network&quot;)&quot;.]]></Details>
<Time><![CDATA[21-06-2016 - 15:46:22]]></Time>
<TimeTick>1466504182</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="20" status="Failed" Source="C:\IFSAutomation\Trunk_IFS_QuestionTypes\Libraries\GeneralLibraries\CommonLibrary.vbs" SourceLine="656" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'objNetwork'<BR>Function file: C:\IFSAutomation\Trunk_IFS_QuestionTypes\Libraries\GeneralLibraries\CommonLibrary.vbs<BR>Line (658): &quot;	currUser = objNetwork.UserName&quot;.]]></Details>
<Time><![CDATA[21-06-2016 - 15:46:23]]></Time>
<TimeTick>1466504183</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="21" status="Failed" Source="C:\IFSAutomation\Trunk_IFS_QuestionTypes\Libraries\GeneralLibraries\CommonLibrary.vbs" SourceLine="657" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="21-06-2016 - 15:43:28" eTime="21-06-2016 - 15:46:23" passed="0" failed="15" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="21-06-2016 - 15:43:23" eTime="21-06-2016 - 15:46:23" passed="0" failed="15" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test SuiteDriver Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>