<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.01" os="Windows 7" host="HW2314"><DocLocation><![CDATA[C:\IFSAutomation\Trunk_IFS_QuestionTypes\Drivers\SuiteDriver]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[SuiteDriver]]></DName>
<Res><![CDATA[Res384]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:01]]></Time>
<TimeTick>1463128741</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Run "iexplore.exe",3]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "iexplore.exe",3]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:01]]></Time>
<TimeTick>1463128741</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="10" status="Passed" >
<Disp><![CDATA[Run "iexplore.exe",3]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="4" nRep="9" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:11]]></Time>
<TimeTick>1463128751</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:11]]></Time>
<TimeTick>1463128751</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Login.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:11]]></Time>
<TimeTick>1463128751</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="15" >
<Disp><![CDATA[Login.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="14" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="13" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj ><![CDATA[Login]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:11]]></Time>
<TimeTick>1463128751</TimeTick>
<NodeArgs eType="User" icon="7" nRep="16" status="Passed" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:11]]></Time>
<TimeTick>1463128751</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:11]]></Time>
<TimeTick>1463128751</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[TXT_user_name.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:11]]></Time>
<TimeTick>1463128751</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="20" >
<Disp><![CDATA[TXT_user_name.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[TXT_user_name.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["chrisj"]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:11]]></Time>
<TimeTick>1463128751</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="22" >
<Disp><![CDATA[TXT_user_name.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="19" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="18" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj ><![CDATA[Login]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:11]]></Time>
<TimeTick>1463128751</TimeTick>
<NodeArgs eType="User" icon="7" nRep="23" status="Passed" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:11]]></Time>
<TimeTick>1463128751</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:11]]></Time>
<TimeTick>1463128751</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[TXT_user_password.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:11]]></Time>
<TimeTick>1463128751</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="27" >
<Disp><![CDATA[TXT_user_password.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[TXT_user_password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["password"]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:11]]></Time>
<TimeTick>1463128751</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="29" >
<Disp><![CDATA[TXT_user_password.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="26" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="25" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj ><![CDATA[Login]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:11]]></Time>
<TimeTick>1463128751</TimeTick>
<NodeArgs eType="User" icon="7" nRep="30" status="Passed" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:11]]></Time>
<TimeTick>1463128751</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:11]]></Time>
<TimeTick>1463128751</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[BTN_Log In.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:11]]></Time>
<TimeTick>1463128751</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="34" >
<Disp><![CDATA[BTN_Log In.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[BTN_Log In.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:11]]></Time>
<TimeTick>1463128751</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="36" >
<Disp><![CDATA[BTN_Log In.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="33" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="32" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj ><![CDATA[Login]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:11]]></Time>
<TimeTick>1463128751</TimeTick>
<NodeArgs eType="User" icon="7" nRep="37" status="Passed" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Work Queue]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:14]]></Time>
<TimeTick>1463128754</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Work Queue]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:14]]></Time>
<TimeTick>1463128754</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[TAB _Home.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:14]]></Time>
<TimeTick>1463128754</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="41" >
<Disp><![CDATA[TAB _Home.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Work Queue.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:14]]></Time>
<TimeTick>1463128754</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="43" >
<Disp><![CDATA[Work Queue.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[TAB _Home.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:16]]></Time>
<TimeTick>1463128756</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="45" >
<Disp><![CDATA[TAB _Home.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="40" >
<Disp><![CDATA[Work Queue]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="39" >
<Disp><![CDATA[Work Queue]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj ><![CDATA[Login]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:19]]></Time>
<TimeTick>1463128759</TimeTick>
<NodeArgs eType="User" icon="7" nRep="46" status="Passed" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Work Queue]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:25]]></Time>
<TimeTick>1463128765</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Work Queue]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:25]]></Time>
<TimeTick>1463128765</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[TAB_Tests.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:25]]></Time>
<TimeTick>1463128765</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="50" >
<Disp><![CDATA[TAB_Tests.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[TAB_Tests.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:25]]></Time>
<TimeTick>1463128765</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="52" >
<Disp><![CDATA[TAB_Tests.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="49" >
<Disp><![CDATA[Work Queue]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="48" >
<Disp><![CDATA[Work Queue]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj ><![CDATA[NavigateToDate]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:25]]></Time>
<TimeTick>1463128765</TimeTick>
<NodeArgs eType="User" icon="7" nRep="53" status="Passed" >
<Disp><![CDATA[NavigateToDate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Work Queue]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:29]]></Time>
<TimeTick>1463128769</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Work Queue]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:29]]></Time>
<TimeTick>1463128769</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[LNK_Test Question Types.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:29]]></Time>
<TimeTick>1463128769</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="57" >
<Disp><![CDATA[LNK_Test Question Types.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[LNK_Test Question Types.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:29]]></Time>
<TimeTick>1463128769</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="59" >
<Disp><![CDATA[LNK_Test Question Types.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="56" >
<Disp><![CDATA[Work Queue]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="55" >
<Disp><![CDATA[Work Queue]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj ><![CDATA[NavigateToDate]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[13-05-2016 - 14:09:29]]></Time>
<TimeTick>1463128769</TimeTick>
<NodeArgs eType="User" icon="7" nRep="60" status="Passed" >
<Disp><![CDATA[NavigateToDate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Navigation Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[13-05-2016 - 14:10:29]]></Time>
<TimeTick>1463128829</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Navigation Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-05-2016 - 14:10:29]]></Time>
<TimeTick>1463128829</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA["DWL_Navigate through Service"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[13-05-2016 - 14:10:29]]></Time>
<TimeTick>1463128829</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="337" status="Warning" >
<Disp><![CDATA["DWL_Navigate through Service"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA["DWL_Navigate through Service"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=WebElement<br>innertext=Navigate through Service Request Grid Simple Condition Blocksselect.*<br>html tag=DIV<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (66 objects found)&nbsp;</FONT></u><br>
micclass=WebElement<br>html tag=DIV<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
html id=<SPAN class=passed> (Used</SPAN>, 46 matches)</SPAN><br>class=panel-body ifs-group-body-single<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>innertext=Navigate through Service Request Grid Simple Condition Blocksselect.*<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[13-05-2016 - 14:10:29]]></Time>
<TimeTick>1463128829</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="338" >
<Disp><![CDATA["DWL_Navigate through Service"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[DWL_Navigate through Service.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-05-2016 - 14:10:29]]></Time>
<TimeTick>1463128829</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="339" >
<Disp><![CDATA[DWL_Navigate through Service.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[DWL_Navigate through Service.Object]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-05-2016 - 14:10:29]]></Time>
<TimeTick>1463128829</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="340" >
<Disp><![CDATA[DWL_Navigate through Service.Object]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[[ All Questions Combined ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-05-2016 - 14:10:31]]></Time>
<TimeTick>1463128831</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="342" >
<Disp><![CDATA[[ All Questions Combined ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[[ Date ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-05-2016 - 14:10:36]]></Time>
<TimeTick>1463128836</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="344" >
<Disp><![CDATA[[ Date ].Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="336" status="Warning" >
<Disp><![CDATA[Navigation Page]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="335" status="Warning" >
<Disp><![CDATA[Navigation Page]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj ><![CDATA[NavigateToDate]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[13-05-2016 - 14:10:36]]></Time>
<TimeTick>1463128836</TimeTick>
<NodeArgs eType="User" icon="7" nRep="345" status="Passed" >
<Disp><![CDATA[NavigateToDate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Navigation Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[13-05-2016 - 14:10:40]]></Time>
<TimeTick>1463128840</TimeTick>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Navigation Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-05-2016 - 14:10:40]]></Time>
<TimeTick>1463128840</TimeTick>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[BTN_Next.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-05-2016 - 14:10:40]]></Time>
<TimeTick>1463128840</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="349" >
<Disp><![CDATA[BTN_Next.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[BTN_Next.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-05-2016 - 14:10:40]]></Time>
<TimeTick>1463128840</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="351" >
<Disp><![CDATA[BTN_Next.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="348" >
<Disp><![CDATA[Navigation Page]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="347" >
<Disp><![CDATA[Navigation Page]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj ><![CDATA[NavigateToDate]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[13-05-2016 - 14:10:40]]></Time>
<TimeTick>1463128840</TimeTick>
<NodeArgs eType="User" icon="7" nRep="352" status="Passed" >
<Disp><![CDATA[NavigateToDate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Dates]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[13-05-2016 - 14:10:44]]></Time>
<TimeTick>1463128844</TimeTick>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA["Dates"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (2 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (2 objects found)&nbsp;</FONT></u><br>
micclass=Browser<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=Dates<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>title=Dates - Internet Explorer<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openurl=http://www.msn.com/en-in/?cobrand=dell13.msn.com&ocid=DELLDHP&pc=MDDCJS<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>opentitle=<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openedbytestingtool=0<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>number of tabs=2<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[13-05-2016 - 14:10:44]]></Time>
<TimeTick>1463128844</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="354" >
<Disp><![CDATA["Dates"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Dates]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-05-2016 - 14:10:44]]></Time>
<TimeTick>1463128844</TimeTick>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[LBL_Date.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-05-2016 - 14:10:44]]></Time>
<TimeTick>1463128844</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="357" >
<Disp><![CDATA[LBL_Date.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[Dates.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-05-2016 - 14:10:44]]></Time>
<TimeTick>1463128844</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="359" >
<Disp><![CDATA[Dates.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="356" >
<Disp><![CDATA[Dates]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA["Dates"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (2 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (2 objects found)&nbsp;</FONT></u><br>
micclass=Browser<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=Dates<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>title=Dates - Internet Explorer<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openurl=http://www.msn.com/en-in/?cobrand=dell13.msn.com&ocid=DELLDHP&pc=MDDCJS<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>opentitle=<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openedbytestingtool=0<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>number of tabs=2<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[13-05-2016 - 14:10:53]]></Time>
<TimeTick>1463128853</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="360" >
<Disp><![CDATA["Dates"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Dates]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-05-2016 - 14:10:53]]></Time>
<TimeTick>1463128853</TimeTick>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[LBL_Date.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-05-2016 - 14:10:53]]></Time>
<TimeTick>1463128853</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="363" >
<Disp><![CDATA[LBL_Date.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="362" >
<Disp><![CDATA[Dates]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="353" >
<Disp><![CDATA[Dates]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj ><![CDATA[NavigateToDate]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[13-05-2016 - 14:10:53]]></Time>
<TimeTick>1463128853</TimeTick>
<NodeArgs eType="User" icon="7" nRep="364" status="Passed" >
<Disp><![CDATA[NavigateToDate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[Dates]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[13-05-2016 - 14:10:57]]></Time>
<TimeTick>1463128857</TimeTick>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[Dates]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-05-2016 - 14:10:57]]></Time>
<TimeTick>1463128857</TimeTick>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[DTL_BusinessDateMaxTest1.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-05-2016 - 14:10:57]]></Time>
<TimeTick>1463128857</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="368" >
<Disp><![CDATA[DTL_BusinessDateMaxTest1.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[[ select ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-05-2016 - 14:10:57]]></Time>
<TimeTick>1463128857</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="370" >
<Disp><![CDATA[[ select ].Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="367" >
<Disp><![CDATA[Dates]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="366" >
<Disp><![CDATA[Dates]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj ><![CDATA[ValidateBusinessDateMaxTest1]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[13-05-2016 - 14:10:57]]></Time>
<TimeTick>1463128857</TimeTick>
<NodeArgs eType="User" icon="7" nRep="371" status="Passed" >
<Disp><![CDATA[ValidateBusinessDateMaxTest1]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[Dates]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[13-05-2016 - 14:10:57]]></Time>
<TimeTick>1463128857</TimeTick>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[Dates]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-05-2016 - 14:10:57]]></Time>
<TimeTick>1463128857</TimeTick>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[LNK_CalendarLeftArrowIcon.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-05-2016 - 14:10:57]]></Time>
<TimeTick>1463128857</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="375" >