<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.01" os="Windows 7" host="HW1419"><DocLocation><![CDATA[C:\IFSAutomation\Finance\Drivers\SuiteDriver]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[SuiteDriver]]></DName>
<Res><![CDATA[Res634]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[11-04-2017 - 19:12:56]]></Time>
<TimeTick>1491918176</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Run "iexplore.exe",3]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "iexplore.exe",3]]></Details>
<Time><![CDATA[11-04-2017 - 19:12:56]]></Time>
<TimeTick>1491918176</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="10" status="Passed" >
<Disp><![CDATA[Run "iexplore.exe",3]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="4" nRep="9" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj ><![CDATA[LoginToSecurityWindow]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:01]]></Time>
<TimeTick>1491918181</TimeTick>
<NodeArgs eType="User" icon="5" nRep="11" status="Passed" >
<Disp><![CDATA[LoginToSecurityWindow]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:41]]></Time>
<TimeTick>1491918221</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Windows Security]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:41]]></Time>
<TimeTick>1491918221</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[txt_UserName.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:41]]></Time>
<TimeTick>1491918221</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="14" >
<Disp><![CDATA[txt_UserName.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[txt_UserName.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["Gallop@IFSAutomation.com"]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:41]]></Time>
<TimeTick>1491918221</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="16" >
<Disp><![CDATA[txt_UserName.SetText]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="13" >
<Disp><![CDATA[Windows Security]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="12" >
<Disp><![CDATA[Browser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj ><![CDATA[LoginToSecurityWindow]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:41]]></Time>
<TimeTick>1491918221</TimeTick>
<NodeArgs eType="User" icon="5" nRep="17" status="Passed" >
<Disp><![CDATA[LoginToSecurityWindow]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:41]]></Time>
<TimeTick>1491918221</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Windows Security]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:41]]></Time>
<TimeTick>1491918221</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[txt_PassWord.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:41]]></Time>
<TimeTick>1491918221</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="20" >
<Disp><![CDATA[txt_PassWord.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[txt_PassWord.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["Password2016!"]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:41]]></Time>
<TimeTick>1491918221</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="22" >
<Disp><![CDATA[txt_PassWord.SetText]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="19" >
<Disp><![CDATA[Windows Security]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="18" >
<Disp><![CDATA[Browser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj ><![CDATA[LoginToSecurityWindow]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:41]]></Time>
<TimeTick>1491918221</TimeTick>
<NodeArgs eType="User" icon="5" nRep="23" status="Passed" >
<Disp><![CDATA[LoginToSecurityWindow]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:41]]></Time>
<TimeTick>1491918221</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Windows Security]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:41]]></Time>
<TimeTick>1491918221</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[btn_OK.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:41]]></Time>
<TimeTick>1491918221</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="26" >
<Disp><![CDATA[btn_OK.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[btn_OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:42]]></Time>
<TimeTick>1491918222</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="28" >
<Disp><![CDATA[btn_OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="25" >
<Disp><![CDATA[Windows Security]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="24" >
<Disp><![CDATA[Browser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj ><![CDATA[LoginToSecurityWindow]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:42]]></Time>
<TimeTick>1491918222</TimeTick>
<NodeArgs eType="User" icon="5" nRep="29" status="Passed" >
<Disp><![CDATA[LoginToSecurityWindow]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:48]]></Time>
<TimeTick>1491918228</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:48]]></Time>
<TimeTick>1491918228</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[btn_Login.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:48]]></Time>
<TimeTick>1491918228</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="33" >
<Disp><![CDATA[btn_Login.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="32" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="31" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj ><![CDATA[LoginToFinance]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:51]]></Time>
<TimeTick>1491918231</TimeTick>
<NodeArgs eType="User" icon="5" nRep="34" status="Passed" >
<Disp><![CDATA[LoginToFinance]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:51]]></Time>
<TimeTick>1491918231</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:51]]></Time>
<TimeTick>1491918231</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[txt_UserName.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:51]]></Time>
<TimeTick>1491918231</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="38" >
<Disp><![CDATA[txt_UserName.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[txt_UserName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["cj"]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:51]]></Time>
<TimeTick>1491918231</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="40" >
<Disp><![CDATA[txt_UserName.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="37" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="36" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj ><![CDATA[LoginToFinance]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:51]]></Time>
<TimeTick>1491918231</TimeTick>
<NodeArgs eType="User" icon="5" nRep="41" status="Passed" >
<Disp><![CDATA[LoginToFinance]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:51]]></Time>
<TimeTick>1491918231</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:51]]></Time>
<TimeTick>1491918231</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[txt_Password.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:51]]></Time>
<TimeTick>1491918231</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="45" >
<Disp><![CDATA[txt_Password.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[txt_Password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["password"]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:51]]></Time>
<TimeTick>1491918231</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="47" >
<Disp><![CDATA[txt_Password.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="44" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="43" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj ><![CDATA[LoginToFinance]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:51]]></Time>
<TimeTick>1491918231</TimeTick>
<NodeArgs eType="User" icon="5" nRep="48" status="Passed" >
<Disp><![CDATA[LoginToFinance]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:51]]></Time>
<TimeTick>1491918231</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:51]]></Time>
<TimeTick>1491918231</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[btn_Login.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:51]]></Time>
<TimeTick>1491918231</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="52" >
<Disp><![CDATA[btn_Login.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[btn_Login.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:51]]></Time>
<TimeTick>1491918231</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="54" >
<Disp><![CDATA[btn_Login.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="51" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="50" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj ><![CDATA[LoginToFinance]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:51]]></Time>
<TimeTick>1491918231</TimeTick>
<NodeArgs eType="User" icon="5" nRep="55" status="Passed" >
<Disp><![CDATA[LoginToFinance]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:56]]></Time>
<TimeTick>1491918236</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Work Queue]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:56]]></Time>
<TimeTick>1491918236</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[lnk_Certificates.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:56]]></Time>
<TimeTick>1491918236</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="59" >
<Disp><![CDATA[lnk_Certificates.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="58" >
<Disp><![CDATA[Work Queue]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="57" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj ><![CDATA[LoginToFinance]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:56]]></Time>
<TimeTick>1491918236</TimeTick>
<NodeArgs eType="User" icon="5" nRep="60" status="Passed" >
<Disp><![CDATA[LoginToFinance]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:56]]></Time>
<TimeTick>1491918236</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Work Queue]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:56]]></Time>
<TimeTick>1491918236</TimeTick>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[lnk_Certificates.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:56]]></Time>
<TimeTick>1491918236</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="64" >
<Disp><![CDATA[lnk_Certificates.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="63" >
<Disp><![CDATA[Work Queue]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="62" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj ><![CDATA[LoginToFinance]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:56]]></Time>
<TimeTick>1491918236</TimeTick>
<NodeArgs eType="User" icon="5" nRep="65" status="Passed" >
<Disp><![CDATA[LoginToFinance]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:57]]></Time>
<TimeTick>1491918237</TimeTick>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Work Queue]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:57]]></Time>
<TimeTick>1491918237</TimeTick>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[lnk_Certificates.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:57]]></Time>
<TimeTick>1491918237</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="69" >
<Disp><![CDATA[lnk_Certificates.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[lnk_Certificates.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:57]]></Time>
<TimeTick>1491918237</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="71" >
<Disp><![CDATA[lnk_Certificates.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="68" >
<Disp><![CDATA[Work Queue]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="67" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj ><![CDATA[NavigateToMasterSummaryPage]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:57]]></Time>
<TimeTick>1491918237</TimeTick>
<NodeArgs eType="User" icon="5" nRep="72" status="Passed" >
<Disp><![CDATA[NavigateToMasterSummaryPage]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:57]]></Time>
<TimeTick>1491918237</TimeTick>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Work Queue]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:57]]></Time>
<TimeTick>1491918237</TimeTick>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[lnk_ClientLookup.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:57]]></Time>
<TimeTick>1491918237</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="76" >
<Disp><![CDATA[lnk_ClientLookup.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[lnk_ClientLookup.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:57]]></Time>
<TimeTick>1491918237</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="78" >
<Disp><![CDATA[lnk_ClientLookup.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="75" >
<Disp><![CDATA[Work Queue]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="74" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj ><![CDATA[NavigateToMasterSummaryPage]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:57]]></Time>
<TimeTick>1491918237</TimeTick>
<NodeArgs eType="User" icon="5" nRep="79" status="Passed" >
<Disp><![CDATA[NavigateToMasterSummaryPage]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:59]]></Time>
<TimeTick>1491918239</TimeTick>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Client Search]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:59]]></Time>
<TimeTick>1491918239</TimeTick>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[lbl_SearchResults.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:59]]></Time>
<TimeTick>1491918239</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="83" >
<Disp><![CDATA[lbl_SearchResults.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="82" >
<Disp><![CDATA[Client Search]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="81" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj ><![CDATA[NavigateToMasterSummaryPage]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:59]]></Time>
<TimeTick>1491918239</TimeTick>
<NodeArgs eType="User" icon="5" nRep="84" status="Passed" >
<Disp><![CDATA[NavigateToMasterSummaryPage]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:59]]></Time>
<TimeTick>1491918239</TimeTick>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[Client Search]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:59]]></Time>
<TimeTick>1491918239</TimeTick>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[lbl_ClientSearchCriteria.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:59]]></Time>
<TimeTick>1491918239</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="88" >
<Disp><![CDATA[lbl_ClientSearchCriteria.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="87" >
<Disp><![CDATA[Client Search]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="86" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj ><![CDATA[NavigateToMasterSummaryPage]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:59]]></Time>
<TimeTick>1491918239</TimeTick>
<NodeArgs eType="User" icon="5" nRep="89" status="Passed" >
<Disp><![CDATA[NavigateToMasterSummaryPage]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:59]]></Time>
<TimeTick>1491918239</TimeTick>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[Client Search]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:59]]></Time>
<TimeTick>1491918239</TimeTick>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[lbl_SearchResults.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:59]]></Time>
<TimeTick>1491918239</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="93" >
<Disp><![CDATA[lbl_SearchResults.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="92" >
<Disp><![CDATA[Client Search]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="91" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj ><![CDATA[NavigateToMasterSummaryPage]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:59]]></Time>
<TimeTick>1491918239</TimeTick>
<NodeArgs eType="User" icon="5" nRep="94" status="Passed" >
<Disp><![CDATA[NavigateToMasterSummaryPage]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:59]]></Time>
<TimeTick>1491918239</TimeTick>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[Client Search]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:59]]></Time>
<TimeTick>1491918239</TimeTick>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[txt_ClientName.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:59]]></Time>
<TimeTick>1491918239</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="98" >
<Disp><![CDATA[txt_ClientName.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T74">
<Obj plainTxt="False" ><![CDATA[txt_ClientName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Heather C"]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:59]]></Time>
<TimeTick>1491918239</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="100" >
<Disp><![CDATA[txt_ClientName.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="97" >
<Disp><![CDATA[Client Search]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="96" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T75">
<Obj ><![CDATA[NavigateToMasterSummaryPage]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:59]]></Time>
<TimeTick>1491918239</TimeTick>
<NodeArgs eType="User" icon="5" nRep="101" status="Passed" >
<Disp><![CDATA[NavigateToMasterSummaryPage]]></Disp>
</NodeArgs>
</Step>
<Step rID="T76">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:59]]></Time>
<TimeTick>1491918239</TimeTick>
<Step rID="T77">
<Obj plainTxt="False" ><![CDATA[Client Search]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:59]]></Time>
<TimeTick>1491918239</TimeTick>
<Step rID="T78">
<Obj plainTxt="False" ><![CDATA[btn_Search.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:59]]></Time>
<TimeTick>1491918239</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="105" >
<Disp><![CDATA[btn_Search.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T79">
<Obj plainTxt="False" ><![CDATA[btn_Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:59]]></Time>
<TimeTick>1491918239</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="107" >
<Disp><![CDATA[btn_Search.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="104" >
<Disp><![CDATA[Client Search]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="103" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T80">
<Obj ><![CDATA[NavigateToMasterSummaryPage]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[11-04-2017 - 19:13:59]]></Time>
<TimeTick>1491918239</TimeTick>
<NodeArgs eType="User" icon="5" nRep="108" status="Passed" >
<Disp><![CDATA[NavigateToMasterSummaryPage]]></Disp>
</NodeArgs>
</Step>
<Step rID="T81">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[11-04-2017 - 19:14:00]]></Time>
<TimeTick>1491918240</TimeTick>
<Step rID="T82">
<Obj plainTxt="False" ><![CDATA[Client Search]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>